name: Probar Ejercicios

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-exercises:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install -g uadyfmat/test-runner
      - run: curl -O https://raw.githubusercontent.com/uadyfmat/test-runner-autoevaluacion-github/main/resources/test-exercises
      - run: bash test-exercises
